export default function Head() {
  return (
    <>
      <title>Wearable Devices Monitoring</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/*<script src="https://unpkg.com/@mongodb-js/charts-embed-dom@beta"></script> */}   
    </>
  )
}
